### ISSUE TITLE
the local server doesn't seem to refresh the css

### ISSUE THREAD

**Issue by andrearicci** [chaos-bodensee/lektor-scss#5]
Hi,
I just started using it but the server seems to refresh *.scss only and not the *.min.css. Here's an output during my scss editing:
```
U scss/style.scss
Finished build in 0.48 sec
Started prune
Finished prune in 0.09 sec
Started build
U scss/style.scss
Finished build in 0.48 sec
Started prune
Finished prune in 0.09 sec
Started build
U scss/style.scss
Finished build in 0.52 sec
Started prune
Finished prune in 0.11 sec
Started build
U scss/style.scss
Finished build in 0.51 sec
Started prune
Finished prune in 0.11 sec
```

While when I stop and restart the server the css is rebuilt. So I have to quit and start the server to see any change:
```
Started source info update
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
Finished source info update in 0.58 sec
Started build
css assets/scss/style.scss ➡ assets/css/style.min.css
U css/style.min.css
Finished build in 1.52 sec
Started prune
Finished prune in 0.12 sec
```
Thank you

[win 10 -- Python 3.11.2 -- Lektor, version 3.4.0b5 -- lektor-scss = 1.4.1]

**Comment by wolf128058** [comment]
Did you use  `lektor build -f scss`  or just `lektor server -f scss` ?

**Comment by andrearicci** [comment]
Hi and thank you for answer.
the second one, `server`, because I'm in production at the moment (I didn't check with `buid`)

**Comment by DO1JLR** [comment]
IIRC you have to choose between minified css output or unminified output. This plugin is not able to generate both. And it doesn't clean up old generated files, it just generates new ones.

@andrearicci Please have a look at the [config file example](https://github.com/chaos-bodensee/lektor-scss/blob/master/configs/scss.ini) as well as the config part in the [README.md](https://github.com/chaos-bodensee/lektor-scss/tree/master#configuration).

**Comment by DO1JLR** [comment]
Feel free to reopen the issue if the problem persists
